version: '3.8'

services:
  # REDIS: Optimiza la carga del mapa de Chosica evitando consultas repetitivas
  redis:
    image: redis:alpine
    container_name: fv_redis
    restart: always
    networks:
      - fv_network

  # BACKEND: API que habla con Hostinger y procesa los datos GIS
  backend:
    build: ./backend
    container_name: fv_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - REDIS_HOST=fv_redis
   
    depends_on:
      - redis
    networks:
      - fv_network

  # FRONTEND: Servidor para la aplicación de React/Vite
  frontend:
    build: ./frontend
    container_name: fv_frontend
    restart: always
    ports:
      - "80:80"
  
    depends_on:
      - backend
    networks:
      - fv_network

networks:
  fv_network:
    driver: bridge