services:
  backend:
    build: ./backend
    container_name: fv_backend
    env_file:
      - ./backend/.env
    environment:
      PORT: 5000
      REDIS_HOST: redis_central
      DB_HOST: mysql_central
      CORS_ALLOWED_ORIGINS: "http://localhost,https://localhost,capacitor://localhost,http://gomap.digital,https://gomap.digital,https://www.gomap.digital,http://localhost:5173,http://192.168.18.2,http://192.168.18.2:5173"
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared-infra
      - traefik.http.routers.backend.rule=(Host(`gomap.digital`) || Host(`www.gomap.digital`)) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=myresolver
      - traefik.http.routers.backend.priority=100
      - traefik.http.services.backend.loadbalancer.server.port=5000
    restart: unless-stopped
    networks:
      - shared-infra

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_PAYPAL_CLIENT_ID: "AfUnH02UYtkQA37IHjbAXahkAscIgR9NGwCQyCR__3ooakMQwXeJJyOU7ehF1WPflTbt_1HNgyNEzlFU"
    container_name: fv_frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared-infra
      - traefik.http.routers.frontend.rule=Host(`gomap.digital`) || Host(`www.gomap.digital`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=myresolver
      - traefik.http.services.frontend.loadbalancer.server.port=80
      - traefik.http.routers.frontend.priority=50
    restart: unless-stopped
    networks:
      - shared-infra


networks:
  shared-infra:
    external: true
